development:
  adapter: postgresql
  encoding: utf8
  database: zing_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: zing_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: zing_production
  pool: 5
  username:
  password:
