# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c28d5bb2993f10834bf84ef432db88b386105e5edc05138c784029722c5fd6e085d04c8f714ddca9201653901eb505d1f5db9e6894ed2dd9562e7885ca723988

test:
  secret_key_base: 86066336e511ee26f8e5c37246933a0634fafd7cb614ba379f521ea255d883762bf71b86dc9211fda40299218de24762dd9a80a0ea0e3dc3b6fe9c82148db40b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
